server.port=8081
spring.application.name=quick-start

# deepseek
spring.ai.deepseek.api-key=${DEEP_SEEK_KEY}
spring.ai.deepseek.chat.options.model=deepseek-chat

# options 通用配置
# 温度，控制生成的文本的随机性，值越大，生成的文本越随机，值越小，生成的文本越确定（0-2 浮点数组）
#spring.ai.deepseek.chat.options.temperature=0.5
# 最大生成的 token 数量，值越大，控制生成的文本越长，值越小，控制生成的文本越短（默认值：1024）
#spring.ai.deepseek.chat.options.max-tokens=1024
# 停止生成的条件，当生成的文本包含这些字符串时，停止生成（默认值：空字符串）
#spring.ai.deepseek.chat.options.stop=END,STOP


# ali百炼
spring.ai.dashscope.api-key=${ALI_AI_KEY}
# 模型名称
spring.ai.dashscope.chat.options.model=qwen-plus

# ollama 配置
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3:4b